# Generated by Django 5.0.4 on 2024-04-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='vanslist',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('year', models.DateTimeField()),
                ('price', models.CharField(max_length=20)),
                ('mileage', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='note',
            name='author',
        ),
    ]
